# Propiedades comunes a TODAS las aplicaciones que piden configuracion.
# Spring Cloud Config las mezcla con las especificas de cada aplicacion.
config.origen=config-server (fichero comun application.properties)
